//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compras()
        {
            this.Impuestos = new HashSet<Impuestos>();
        }
    
        public int Id { get; set; }
        public string Compra { get; set; }
        public int Producto_Id { get; set; }
        public int Empresa_Id { get; set; }
        public decimal Cantidad { get; set; }
        public Nullable<decimal> CostoUnitario { get; set; }
        public Nullable<decimal> CostoTotal { get; set; }
        public Nullable<decimal> CostoNeto { get; set; }
        public Nullable<decimal> GranTotal { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Empresas Empresas { get; set; }
        public virtual Productos Productos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Impuestos> Impuestos { get; set; }
    }
}
