//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Impuestos
    {
        public int Id { get; set; }
        public string Impuesto { get; set; }
        public decimal Porcentaje { get; set; }
        public decimal Monto { get; set; }
        public Nullable<int> Venta_Id { get; set; }
        public Nullable<int> Compra_Id { get; set; }
        public bool Estatus { get; set; }
    
        public virtual Compras Compras { get; set; }
        public virtual Ventas Ventas { get; set; }
    }
}
